### ISSUE TITLE
Pandas 1.4.1: Error in metrics data time calculation

### ISSUE THREAD

**Issue by akey7** [WISDEM/WOMBAT#36]
![Screen Shot 2022-03-17 at 12 02 21 PM](https://user-images.githubusercontent.com/2609896/158866773-c41417e6-f57e-4824-9828-fcd0db450191.png)

**Comment by RHammond2** [comment]
Thanks for submitting this issue, and walking me through it, @akey7! It seems like the best option was to individually set each column value throughout this module to avoid the error in multiple methods.
